from __future__ import annotations

from typing import Protocol

from .models import Artifact, ProjectContext, RunSession, Task


class ContextStore(Protocol):
    def load(self) -> ProjectContext: ...
    def load_markdown(self) -> str: ...
    def save(self, context: ProjectContext, markdown: str | None = None) -> ProjectContext: ...


class TaskStore(Protocol):
    def list(self) -> list[Task]: ...
    def get(self, task_id: str) -> Task | None: ...
    def save(self, task: Task) -> Task: ...


class ArtifactStore(Protocol):
    def list(self) -> list[Artifact]: ...
    def get(self, artifact_id: str) -> Artifact | None: ...
    def save(self, artifact: Artifact) -> Artifact: ...


class RunStore(Protocol):
    def list_for_task(self, task_id: str) -> list[RunSession]: ...
    def save(self, run: RunSession) -> RunSession: ...
    def save_packet(self, packet_name: str, content: str): ...
    def load_packet(self, packet_name: str) -> str: ...


class PromptHandoffService(Protocol):
    def create_pm_packet(self, task: Task, context_markdown: str, skill_text: str) -> str: ...
    def create_critic_packet(
        self,
        task: Task,
        context_markdown: str,
        critic_skill_text: str,
        pm_output_markdown: str,
    ) -> str: ...
